displayName=Ghostly Vision
author=Endrit
description=(Formerly Visibility Enhancer) Teammate opacity, ground-view filters, and outlines for raids.
tags=Ghostly Vision,vision,visibility,visibility enhancer,opacity,entity,hider,entity hider,raids,raid,raids visibility enhancer,raids entity hider,toa,cox,tob,tombs of amascut,theatre of blood,chambers of xeric
plugins=com.visibilityenhancer.VisibilityEnhancer