displayName=Visibility Enhancer
author=Endrit
description=Adjusts opacity and silhouettes for yourself and other players.
tags=visibility,opacity,entity,hider
plugins=com.visibilityenhancer.VisibilityEnhancer